[project]
name = "test-whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.8",
    "faster-whisper>=1.1.1",
    "uvicorn>=0.34.0",
]
